all:
  hosts:
    server2:
      ansible_connection: ssh
      ansible_user: root
      ansible_host: 192.168.10.105
      ansible_port: 22
      ansible_ssh_private_key_file: iac/key-fake-test/ubuntu-key